Improved deposition parametrisation
metno/snap pull request #134
Opened 2024-10-16 11:18 UTC by magnusuMET

This is the parametrisation dry deposition and wet deposition as implemented in the two papers. All schemes are selectable through the input file, but will require specialised input for dry deposition and wet deposition in the form of an ancillary landuse file and arome meteorology.

This PR will be followed up by adapting to different sources of meteorology.

2024-10-17 14:35 UTC, heikoklein reviewed
We still need to discuss if we need all ddep/wdep schemes which makes will not be used.

2024-10-17 14:35 UTC, heikoklein commented on src/common/drydep.f90
>      else
Can you make 0.002 and 0.008 parameters, e.g.
```
real, parameter :: vc_gas = 0.008 ! ddep velocity for gasses in m/s
real, parameter :: vc_part = 0.002 ! ddep velocity for particles in m/s
```

2024-10-17 14:35 UTC, heikoklein commented on src/common/drydep.f90
> +  real(real64), parameter :: z = 30 ! Assumed height of surface/constant flux layer
is z in line 171 == h in line 138? Should be one parameter for the complete ddep-code.

2024-11-25 13:31 UTC, heikoklein requested changes
Thanks for adding the new meteorological parameters.

All meteorological parameters should be declared in [snapmetML.f90](https://github.com/metno/snap/blob/master/src/common/snapmetML.f90) so they can be found easily.

Since old ecemep files don't have the new parameters, we will have problems with our archive for the next 25 days and with older runs saved elsewhere. It would be an advantage to have these parameters as optional.

We would like to use these new fields also for other met-inputs, in particular for ec_det but also for era5, so they shouldn't be hardcoded to ecemep.

2024-11-25 14:58 UTC, magnusuMET commented
The parametrisation is still not enabled in the snap.input files created by the frontend, which will come in a separate PR

2025-02-13 12:51 UTC, merged